### ISSUE TITLE
Attachment Indexer needs updated package.

### ISSUE THREAD

**Issue by bmcdavid** [TCB-Internet-Solutions/vulcan#3]
Search Provider extensions were moved from core, but the file extension function remained in different core extension class. The current package tries to use SearchProviderExtensions.cs which no longer exits as noted below:

```
2017-05-10 16:24:45,950 [25] ERROR TcbInternetSolutions.Vulcan.Core.Implementation.VulcanClient: Vulcan could not index content with content link 1328 for language invariant: 
Elasticsearch.Net.UnexpectedElasticsearchClientException: Could not load type 'TcbInternetSolutions.Vulcan.Core.Extensions.SearchProviderExtensions' from assembly 'TcbInternetSolutions.Vulcan.Core, Version=2.3.2.0, Culture=neutral, PublicKeyToken=null'. ---> System.TypeLoadException: Could not load type 'TcbInternetSolutions.Vulcan.Core.Extensions.SearchProviderExtensions' from assembly 'TcbInternetSolutions.Vulcan.Core, Version=2.3.2.0, Culture=neutral, PublicKeyToken=null'.
   at TcbInternetSolutions.Vulcan.AttachmentIndexer.Implementation.VulcanAttachmentInspector.AllowIndexing(MediaData media)
   at TcbInternetSolutions.Vulcan.AttachmentIndexer.VulcanAttachmentIndexModifier.ProcessContent(IContent content, Stream writableStream)
   at TcbInternetSolutions.Vulcan.Core.Implementation.VulcanCustomJsonSerializer.Serialize(Object data, Stream writableStream, SerializationFormatting formatting)
   at Elasticsearch.Net.PostData`1.Write(Stream writableStream, IConnectionConfigurationValues settings) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Transport\PostData.cs:line 104
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 119
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TReturn](RequestData requestData) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 414
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Transport\Transport.cs:line 69
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Transport\Transport.cs:line 89
   at Nest.LowLevelDispatch.IndexDispatch[T](IRequest`1 p, PostData`1 body) in C:\Users\russ\source\elasticsearch-net-2.x\src\Nest\_Generated\_LowLevelDispatch.generated.cs:line 996
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch) in C:\Users\russ\source\elasticsearch-net-2.x\src\Nest\ElasticClient.cs:line 56
   at TcbInternetSolutions.Vulcan.Core.Implementation.VulcanClient.IndexContent(IContent content)
Elasticsearch.Net.UnexpectedElasticsearchClientException: Could not load type 'TcbInternetSolutions.Vulcan.Core.Extensions.SearchProviderExtensions' from assembly 'TcbInternetSolutions.Vulcan.Core, Version=2.3.2.0, Culture=neutral, PublicKeyToken=null'. ---> System.TypeLoadException: Could not load type 'TcbInternetSolutions.Vulcan.Core.Extensions.SearchProviderExtensions' from assembly 'TcbInternetSolutions.Vulcan.Core, Version=2.3.2.0, Culture=neutral, PublicKeyToken=null'.
   at TcbInternetSolutions.Vulcan.AttachmentIndexer.Implementation.VulcanAttachmentInspector.AllowIndexing(MediaData media)
   at TcbInternetSolutions.Vulcan.AttachmentIndexer.VulcanAttachmentIndexModifier.ProcessContent(IContent content, Stream writableStream)
   at TcbInternetSolutions.Vulcan.Core.Implementation.VulcanCustomJsonSerializer.Serialize(Object data, Stream writableStream, SerializationFormatting formatting)
   at Elasticsearch.Net.PostData`1.Write(Stream writableStream, IConnectionConfigurationValues settings) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Transport\PostData.cs:line 104
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 119
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TReturn](RequestData requestData) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 414
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Transport\Transport.cs:line 69
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\Users\russ\source\elasticsearch-net-2.x\src\Elasticsearch.Net\Transport\Transport.cs:line 89
   at Nest.LowLevelDispatch.IndexDispatch[T](IRequest`1 p, PostData`1 body) in C:\Users\russ\source\elasticsearch-net-2.x\src\Nest\_Generated\_LowLevelDispatch.generated.cs:line 996
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch) in C:\Users\russ\source\elasticsearch-net-2.x\src\Nest\ElasticClient.cs:line 56
   at TcbInternetSolutions.Vulcan.Core.Implementation.VulcanClient.IndexContent(IContent content)
```

**Comment by bmcdavid** [comment]
Resolved with 0.3.2 of TcbInternetSolutions.Vulcan.AttachmentIndexer.

http://nuget.episerver.com/en/OtherPages/Package/?packageId=TcbInternetSolutions.Vulcan.AttachmentIndexer
